# Generated by Django 3.0.3 on 2020-03-04 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=60)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=20)),
                ('summary', models.TextField(blank=True)),
                ('place_img', models.ImageField(default='./assets/locations/default.jpg', upload_to='./assets/locations/')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=1)),
                ('price', models.PositiveIntegerField()),
                ('dest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranports_to', to='map_db.Location')),
                ('src_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranports_from', to='map_db.Location')),
            ],
        ),
    ]
