# Generated by Django 3.0.3 on 2020-03-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place_img',
            field=models.ImageField(default='map_db/assets/locations/default.jpg', upload_to='map_db/assets/locations/'),
        ),
    ]
