# Generated by Django 3.0.3 on 2020-03-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_db', '0002_auto_20200304_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place_img',
            field=models.ImageField(default='assets/locations/default.jpg', upload_to='assets/locations/'),
        ),
    ]
