# Generated by Django 3.0.3 on 2020-02-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_nav', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('lat', 'lng')},
        ),
    ]
